### ISSUE TITLE
File name is too long and does not work !

### ISSUE THREAD

**Issue by AhmadQatar** [pH-7/QRCode-Generator-PHP-Class#4]
this exmp for location url from google map

mysites/qrcode_files/qr-L1-www.google.com.qa_2Fmaps_2Fplace_2F25_25C2_25B017_2727.5_2522N_2B51_25C2_25B032_2748.7_2522E_2F_4025.2922823_2C51.5469781_2C17.44z_2Fdata_3D_214m5_213m4_211s0x0_3A0x0_218m2_213d25.2909722_214d51.5468611_3Fhl_3Den.png

does not work , can you fix it ?

Thanks

**Comment by pH-7** [comment]
Hi! @AhmadQatar! What error message do you have? I will test it and post a fix ASAP. Just before that, please post below the code you did calling this QRCode class.

**Comment by AhmadQatar** [comment]
hi, this error message :

( ! ) Warning: imagepng(wp-content/uploads/qrcode_files/qr-L1- (here url)
failed to open stream: No such file or directory in (my path dir)

thanks

**Comment by AhmadQatar** [comment]
when i use small URL it's OK put the long url not accept !

**Comment by pH-7** [comment]
This issue from wordpress or PHP but not from THIS class. Again, if this doesn't work, maybe it's from the Google Chart API.
