### ISSUE TITLE
profile image

### ISSUE THREAD

**Issue by kdsn** [pH-7/QRCode-Generator-PHP-Class#5]
when I scan the qr code from the example, the image does not show. Any ideas as to where the problem lies?

scanned with an iPhone

**Comment by pH-7** [comment]
Once you add it through Composer (or include the file manually), please try the following 
```php
require_once 'vendor/autoload.php';
$oQRC = new QRCode; 
$oQRC->fullName('KDSN') 
    ->nickName('My NAME') 
    ->gender('M')
    ->finish();

$oQRC->display(); 
```
Let me know what you see

**Comment by kdsn** [comment]
sorry I was not specific enough. 
I've tried the example, and everything works as it should, except the picture, it just shows the initials.

**Comment by pH-7** [comment]
Oh, sorry about the confusion then! 

Please try with another image format, maybe... Try with another URL (web host).
The problem must come somewhere in this https://github.com/pH-7/QRCode-Generator-PHP-Class/blob/master/QRCode.class.php#L201-L214
