### ISSUE TITLE
Google API!

### ISSUE THREAD

**Issue by E000001** [pH-7/QRCode-Generator-PHP-Class#8]
Maybe, you should inform all that you are using Google API in your script!

**Comment by pH-7** [comment]
Hey @E000001 
I do!, and pretty much everywhere I would say... 😊
You just have to be able to read... see below 🙂

## On the GitHub Repository Description
![google-api](https://user-images.githubusercontent.com/1325411/54253267-1b3dac80-45b3-11e9-9056-d0106d012f74.png)

## On the README file
![google-api-2](https://user-images.githubusercontent.com/1325411/54253266-1aa51600-45b3-11e9-9893-207d401532ef.png)

## On the Packagist page
![google-api-composer](https://user-images.githubusercontent.com/1325411/54253265-1aa51600-45b3-11e9-9332-62a9755b0514.png)

**Comment by pH-7** [comment]
Why? Is Google Chart API a problem for you?

**Comment by gambit75** [comment]
I think the issue is the OLD API has been deprecated and shut down.  The new API doesn't have QR charts.  From what I have searched a another API we can use is here http://goqr.me/api/
